id: I7FD16B33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:20:27+00:00'
last_modified: '2022-06-09T07:53:22.789293+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16464
  title: མཁས་དབང་བློ་བཟང་རྒྱ་མཚོའི་བློ་རིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    04FE:
      image_group_id: I1KG16470
      title: Volume 1 of mkhas dbang blo bzang rgya mtsho'i blo rigs/
      total_pages: 300
      order: 1
      base_file: 04FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
