id: P007949
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16464
  title: མཁས་དབང་བློ་བཟང་རྒྱ་མཚོའི་བློ་རིགས།
  author: ''
  volumes:
    a749c698eb4b4913ada4b5c331682e2c:
      image_group_id: I1KG16470
      title: Volume 1 of mkhas dbang blo bzang rgya mtsho'i blo rigs/
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
