id: P007949
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16464
  title: མཁས་དབང་བློ་བཟང་རྒྱ་མཚོའི་བློ་རིགས།
  author: ''
  volumes:
    9d7bf9cc1b2641ffacfc8bc4ea49ded0:
      image_group_id: I1KG16470
      title: ''
      volume_number: 1
      total_pages: 300
ebook_metadata:
  title: མཁས་དབང་བློ་བཟང་རྒྱ་མཚོའི་བློ་རིགས།
  author: ''
  sku: P007949
  cover: cover.jpg
  layers:
  - pagination
